export const SUBCATEGORIES_BY_CATEGORY: Record<string, string[]> = {
  "Music and Entertainment": [
    "Rock",
    "Pop",
    "Hip-Hop & Rap",
    "Electronic Music",
    "Jazz & Blues",
    "Classical Music",
    "K-Pop",
    "R&B & Soul",
    "Reggae & Latin",
  ],
  "Arts": [
    "Painting & Sculpture",
    "Cinema",
    "Photography",
    "Architecture",
    "Theater",
    "Literature",
    "Dance",
    "Fashion & Design",
  ],
  "Military": [
    "Battles & Wars",
    "Military Strategy",
    "Weapons & Technology",
    "Navy & Air Force",
    "Special Forces",
    "Military Leaders",
    "Nuclear Weapons",
    "Peacekeeping",
  ],
  "Religion": [
    "Christianity",
    "Islam",
    "Judaism",
    "Buddhism",
    "Hinduism",
    "Indigenous Religions",
    "New Religious Movements",
    "Mythology",
  ],
  "Criminals": [
    "Serial Killers",
    "Organized Crime",
    "White Collar Crime",
    "Drug Lords",
    "Hackers & Cybercrime",
    "Historical Criminals",
    "Heists & Robberies",
    "War Criminals",
  ],
  "Politics": [
    "Geopolitics",
    "Human Rights",
    "Democracy & Elections",
    "International Relations",
    "Social Movements",
    "Political History",
    "International Organizations",
    "Law & Constitutions",
  ],
  "Sciences": [
    "Physics",
    "Biology",
    "Chemistry",
    "Astronomy & Space",
    "Medicine & Health",
    "Technology",
    "Mathematics",
    "Psychology",
    "Environment",
  ],
  "Philosophy": [
    "African Philosophy",
    "Confucianism",
    "Eastern Philosophy",
    "Indigenous American Philosophy",
    "Latin American Philosophy",
    "Middle Eastern Philosophy",
    "Western Philosophy",
  ],
  "Pop Culture": [
    "Memes & Internet",
    "Actors & Actresses",
    "Dancers",
    "Famous For Being Famous",
    "Film & TV Crew",
    "Hosts & Presenters",
    "Models",
    "News & Journalists",
    "People of Classic Hollywood",
    "Voice Acting",
    "Animation",
    "Anime & Manga",
    "Video Games",
    "Celebrities",
    "Comics",
  ],
};
